# Correlation between HDI and GDP (PPP) per capita

In this test case we'll try to use Pandas to verify if there is correlation between HDI and GDP (PPP) per capita. This is kinda obvious, but this is a way to show the power of this tool.

First let's get information about HDI.

In [1]:
import pandas as pd

hdi_url = 'https://countryeconomy.com/hdi'
hdiDFs = pd.read_html(hdi_url)
hdiDFs

[              Countries    HDI HDI Ranking  HDI Ranking.1  Ch.
 0     United States [+]  0.924         13º            NaN  1.0
 1    United Kingdom [+]  0.922         14º            NaN  0.0
 2           Germany [+]  0.936          5º            NaN  1.0
 3            France [+]  0.901         24º            NaN  0.0
 4             Japan [+]  0.909         19º            NaN  0.0
 ..                  ...    ...         ...            ...  ...
 184           Samoa [+]  0.713        104º            NaN  0.0
 185           Yemen [+]  0.452        178º            NaN  6.0
 186    South Africa [+]  0.699        113º            NaN  2.0
 187          Zambia [+]  0.588        144º            NaN  3.0
 188        Zimbabwe [+]  0.535        156º            NaN  1.0

 [189 rows x 5 columns]]

The DataFrame that matters to us is in the first position of the list of captured DataFrames.

In [2]:
hdi = hdiDFs[0]
hdi

              Countries    HDI HDI Ranking  HDI Ranking.1  Ch.
0     United States [+]  0.924         13º            NaN  1.0
1    United Kingdom [+]  0.922         14º            NaN  0.0
2           Germany [+]  0.936          5º            NaN  1.0
3            France [+]  0.901         24º            NaN  0.0
4             Japan [+]  0.909         19º            NaN  0.0
..                  ...    ...         ...            ...  ...
184           Samoa [+]  0.713        104º            NaN  0.0
185           Yemen [+]  0.452        178º            NaN  6.0
186    South Africa [+]  0.699        113º            NaN  2.0
187          Zambia [+]  0.588        144º            NaN  3.0
188        Zimbabwe [+]  0.535        156º            NaN  1.0

[189 rows x 5 columns]

Now let's capture information about about adjusted per capita income.

In [3]:
income_url = 'https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)_per_capita'
incomeDFs = pd.read_html(income_url)
incomeDFs

[                                                   0  \
 0  > 50,000 35,000–50,000 20,000–35,000 10,000–20...

                                           1
 0  5,000–10,000 2,000–5,000 < 2,000 No data  ,
                                                      0  \
 0                International Monetary Fund (2018)[4]
 1    Rank Country/Territory Int$ 1  Qatar 130,475 —...
 2                                                 Rank
 3                                                    1
 4                                                    —
 ..                                                 ...
 612                                                189
 613                                                190
 614                                                191
 615                                                192
 616                                                193

                                                      1  \
 0                              World Bank (2018)[5][6]
 1    Rank Country/Territory Int$ 1  Qatar 126,898 —...
 2                                    Country/Territory
 3                                                Qatar
 4                                                Macau
 ..                                                 ...
 612                                            Liberia
 613                  Congo, Democratic Republic of the
 614                                            Burundi
 615                           Central African Republic
 616                                            Somalia

                                                      2          3
 0           Central Intelligence Agency (1993–2017)[7]        NaN
 1    Rank Country/Territory Int$ Year 1  Liechtenst...        NaN
 2                                                 Int$        NaN
 3                                               130475        NaN
 4                                               116808        NaN
 ..                                                 ...        ...
 612                                                900  2017 est.
 613                                                800  2017 est.
 614                                                800  2017 est.
 615                                                700  2017 est.
 616                                                NaN  2017 est.

 [617 rows x 4 columns],
     Rank         Country/Territory      Int$
 0      1                     Qatar  130475.0
 1      —                     Macau  116808.0
 2      2                Luxembourg  106705.0
 3      3                 Singapore  100345.0
 4      4                    Brunei   79530.0
 ..   ...                       ...       ...
 189  184                   Burundi     732.0
 190  185  Central African Republic     712.0
 191  NaN                       NaN       NaN
 192    —                     Syria       NaN
 193    —                 Venezuela       NaN

 [194 rows x 3 columns],
     Rank                  Country/Territory    Int$
 0      1                              Qatar  126898
 1      —                              Macau  123892
 2      2                         Luxembourg  113337
 3      3                          Singapore  101531
 4      4                            Ireland   83203
 ..   ...                                ...     ...
 183  178                            Liberia    1308
 184  179                              Niger    1063
 185  180  Congo, Democratic Republic of the     932
 186  181           Central African Republic     859
 187  182                            Burundi     744

 [188 rows x 3 columns],
     Rank                  Country/Territory      Int$       Year
 0      1                      Liechtenstein  139100.0  2009 est.
 1      2                              Qatar  124900.0  2017 est.
 2      3                             Monaco  115700.0  2015 est.
 3      —                              Macau  114400.0  2017 est.
 4      4                         Luxembourg  109100.0  2017 est.
 ..   ...                                ...       ...        ...
 225  189                            Liberia     900.0  2017 est.
 226  190  Congo, Democratic Republic of the     800.0  2017 est.
 227  191                            Burundi     800.0  2017 est.
 228  192           Central African Republic     700.0  2017 est.
 229  193                            Somalia       NaN  2017 est.

 [230 rows x 4 columns],
                                                     0  \
 0                  International Monetary Fund (2017)
 1   Rank Country/Territory Type 1  Qatar Oil & Gas...
 2                                                Rank
 3                                                   1
 4                                                   —
 5                                                   2
 6                                                   3
 7                                                   4
 8                                                   5
 9                                                   6
 10                                                  7
 11                                                  8
 12                                                  9
 13                                                  —
 14                                                 10
 15                                                 11
 16                                                 12
 17                                                 13
 18                                                 14
 19                                                 15
 20                                               Rank
 21                                                  1
 22                                                  2
 23                                                  —
 24                                                  3
 25                                                  4
 26                                                  5
 27                                                  6
 28                                                  7
 29                                                  8
 30                                                  —
 31                                                  9
 32                                                 10
 33                                                 11
 34                                                 12
 35                                                 13
 36                                                 14
 37                                                 15

                                                     1  \
 0                             World Bank (2016)[5][6]
 1   Rank Country/Territory Type 1  Qatar Oil & Gas...
 2                                   Country/Territory
 3                                               Qatar
 4                                               Macau
 5                                          Luxembourg
 6                                           Singapore
 7                                              Brunei
 8                                             Ireland
 9                                              Norway
 10                                             Kuwait
 11                               United Arab Emirates
 12                                        Switzerland
 13                                          Hong Kong
 14                                         San Marino
 15                                      United States
 16                                       Saudi Arabia
 17                                        Netherlands
 18                                            Iceland
 19                                            Bahrain
 20                                  Country/Territory
 21                                              Qatar
 22                                         Luxembourg
 23                                              Macau
 24                                          Singapore
 25                                             Brunei
 26                               United Arab Emirates
 27                                            Ireland
 28                                        Switzerland
 29                                             Norway
 30                                          Hong Kong
 31                                      United States
 32                                       Saudi Arabia
 33                                            Iceland
 34                                        Netherlands
 35                                            Austria
 36                                            Denmark
 37                                             Sweden

                                  2
 0                              NaN
 1                              NaN
 2                             Type
 3                        Oil & Gas
 4             Tax haven (Sink OFC)
 5      Top 10 Tax haven (Sink OFC)
 6   Top 10 Tax haven (Conduit OFC)
 7                        Oil & Gas
 8   Top 10 Tax haven (Conduit OFC)
 9                        Oil & Gas
 10                       Oil & Gas
 11                       Oil & Gas
 12  Top 10 Tax Haven (Conduit OFC)
 13     Top 10 Tax Haven (Sink OFC)
 14            Tax haven (Sink OFC)
 15                           59495
 16                       Oil & Gas
 17  Top 10 Tax Haven (Conduit OFC)
 18                           52150
 19                       Oil & Gas
 20                            Type
 21                       Oil & Gas
 22     Top 10 Tax haven (Sink OFC)
 23            Tax haven (Sink OFC)
 24  Top 10 Tax haven (Conduit OFC)
 25                       Oil & Gas
 26                       Oil & Gas
 27  Top 10 Tax haven (Conduit OFC)
 28  Top 10 Tax haven (Conduit OFC)
 29                       Oil & Gas
 30     Top 10 Tax haven (Sink OFC)
 31                           57467
 32                       Oil & Gas
 33                           51399
 34  Top 10 Tax haven (Conduit OFC)
 35                           50078
 36                           49496
 37                           49175  ,
    Rank     Country/Territory                            Type
 0     1                 Qatar                       Oil & Gas
 1     —                 Macau            Tax haven (Sink OFC)
 2     2            Luxembourg     Top 10 Tax haven (Sink OFC)
 3     3             Singapore  Top 10 Tax haven (Conduit OFC)
 4     4                Brunei                       Oil & Gas
 5     5               Ireland  Top 10 Tax haven (Conduit OFC)
 6     6                Norway                       Oil & Gas
 7     7                Kuwait                       Oil & Gas
 8     8  United Arab Emirates                       Oil & Gas
 9     9           Switzerland  Top 10 Tax Haven (Conduit OFC)
 10    —             Hong Kong     Top 10 Tax Haven (Sink OFC)
 11   10            San Marino            Tax haven (Sink OFC)
 12   11         United States                           59495
 13   12          Saudi Arabia                       Oil & Gas
 14   13           Netherlands  Top 10 Tax Haven (Conduit OFC)
 15   14               Iceland                           52150
 16   15               Bahrain                       Oil & Gas,
    Rank     Country/Territory                            Type
 0     1                 Qatar                       Oil & Gas
 1     2            Luxembourg     Top 10 Tax haven (Sink OFC)
 2     —                 Macau            Tax haven (Sink OFC)
 3     3             Singapore  Top 10 Tax haven (Conduit OFC)
 4     4                Brunei                       Oil & Gas
 5     5  United Arab Emirates                       Oil & Gas
 6     6               Ireland  Top 10 Tax haven (Conduit OFC)
 7     7           Switzerland  Top 10 Tax haven (Conduit OFC)
 8     8                Norway                       Oil & Gas
 9     —             Hong Kong     Top 10 Tax haven (Sink OFC)
 10    9         United States                           57467
 11   10          Saudi Arabia                       Oil & Gas
 12   11               Iceland                           51399
 13   12           Netherlands  Top 10 Tax haven (Conduit OFC)
 14   13               Austria                           50078
 15   14               Denmark                           49496
 16   15                Sweden                           49175,
                vteLists of countries by GDP rankings  \
 0                      Purchasing power parity (PPP)
 1                                            Nominal
 2                                        Growth rate
 3                        Gross national income (GNI)
 4                                Countries by region
 5                              Subnational divisions
 6  Lists of countries by financial rankings List ...

              vteLists of countries by GDP rankings.1
 0  Per capita Past per capita Past and projected ...
 1  Per capita Past and projected per capita Secto...
 2  African countries Asian states European Union ...
 3                  PPP per capita Nominal per capita
 4  Africa PPP nominal Commonwealth of Nations PPP...
 5  Argentina Australia Austria Belgium Brazil Bul...
 6  Lists of countries by financial rankings List ...  ,
               vteEconomic classification of countries  \
 0   Developed country Developing country Least Dev...
 1                                   Three-World Model
 2                        Gross domestic product (GDP)
 3                                             Nominal
 4                       Purchasing power parity (PPP)
 5                         Gross national income (GNI)
 6                                               Wages
 7                                              Wealth
 8                             Other national accounts
 9                                   Human development
 10                                     Digital divide
 11       Net international investment position (NIIP)

             vteEconomic classification of countries.1
 0   Developed country Developing country Least Dev...
 1   First World Second World Third World Fourth World
 2   Nominal By country past and projected per capi...
 3   By country past and projected per capita per c...
 4   By country future estimates per capita per cap...
 5   (Nominal, Atlas method) per capita (PPP) per c...
 6   Average wage Europe by monthly average wage Em...
 7                                    Wealth per adult
 8   Gross National Happiness Net material product ...
 9   Human Development Index by country inequality-...
 10  ICT Development Index Number of broadband Inte...
 11                                         Per capita  ,
                                0  \
 0                        Nominal
 1  Purchasing power parity (PPP)

                                                    1
 0  By country past and projected per capita per c...
 1  By country future estimates per capita per cap...  ,
          vteLists of countries by financial rankings  \
 0                                              Trade
 1                                         Investment
 2                                              Funds
 3                                    Budget and debt
 4                                   Income and taxes
 5                                         Bank rates
 6                                           Currency
 7                                              Other
 8  Lists of countries by GDP rankings List of int...

        vteLists of countries by financial rankings.1
 0  Account balance % of GDP Exports net per capit...
 1                   FDI received past FDI abroad GFI
 2  Forex reserves Forex reserves (ex. gold) Gold ...
 3  Government budget PPP % of GDP Credit rating E...
 4  Tax rates Tax revenue Wage average median minimum
 5  Central bank interest rate Commercial bank pri...
 6               Exchange rates to US$ Inflation rate
 7  Financial Development Index Corporate governan...
 8  Lists of countries by GDP rankings List of int...  ]

The DataFrame that matters to us is in the fifth position of the list of DFs, wel'll therefore use it as our income data.

In [4]:
income = incomeDFs[4]
income

    Rank                  Country/Territory      Int$       Year
0      1                      Liechtenstein  139100.0  2009 est.
1      2                              Qatar  124900.0  2017 est.
2      3                             Monaco  115700.0  2015 est.
3      —                              Macau  114400.0  2017 est.
4      4                         Luxembourg  109100.0  2017 est.
..   ...                                ...       ...        ...
225  189                            Liberia     900.0  2017 est.
226  190  Congo, Democratic Republic of the     800.0  2017 est.
227  191                            Burundi     800.0  2017 est.
228  192           Central African Republic     700.0  2017 est.
229  193                            Somalia       NaN  2017 est.

[230 rows x 4 columns]

Now we have our two DataFrames. Let's take a look at them again.

In [5]:
hdi

              Countries    HDI HDI Ranking  HDI Ranking.1  Ch.
0     United States [+]  0.924         13º            NaN  1.0
1    United Kingdom [+]  0.922         14º            NaN  0.0
2           Germany [+]  0.936          5º            NaN  1.0
3            France [+]  0.901         24º            NaN  0.0
4             Japan [+]  0.909         19º            NaN  0.0
..                  ...    ...         ...            ...  ...
184           Samoa [+]  0.713        104º            NaN  0.0
185           Yemen [+]  0.452        178º            NaN  6.0
186    South Africa [+]  0.699        113º            NaN  2.0
187          Zambia [+]  0.588        144º            NaN  3.0
188        Zimbabwe [+]  0.535        156º            NaN  1.0

[189 rows x 5 columns]

In [6]:
income

    Rank                  Country/Territory      Int$       Year
0      1                      Liechtenstein  139100.0  2009 est.
1      2                              Qatar  124900.0  2017 est.
2      3                             Monaco  115700.0  2015 est.
3      —                              Macau  114400.0  2017 est.
4      4                         Luxembourg  109100.0  2017 est.
..   ...                                ...       ...        ...
225  189                            Liberia     900.0  2017 est.
226  190  Congo, Democratic Republic of the     800.0  2017 est.
227  191                            Burundi     800.0  2017 est.
228  192           Central African Republic     700.0  2017 est.
229  193                            Somalia       NaN  2017 est.

[230 rows x 4 columns]

I want both DataFrames to have only two columns: the name of the country and the index. We'll have to format our DFs in order to achieve this. Let's start with the HDI DataFrame.

In [7]:
hdi.drop(['HDI Ranking', 'HDI Ranking.1', 'Ch.'] , 1, inplace=True)
hdi

              Countries    HDI
0     United States [+]  0.924
1    United Kingdom [+]  0.922
2           Germany [+]  0.936
3            France [+]  0.901
4             Japan [+]  0.909
..                  ...    ...
184           Samoa [+]  0.713
185           Yemen [+]  0.452
186    South Africa [+]  0.699
187          Zambia [+]  0.588
188        Zimbabwe [+]  0.535

[189 rows x 2 columns]

I want the names of the columns of my DataFrames to be standardized to *Country*, *HDI* and *GDP (PPP) percapita (U$)*, therefore I need to rename one of the columns in my HDI DataFrame.

In [8]:
hdi.rename(columns={'Countries': 'Country'}, inplace=True)
hdi

                Country    HDI
0     United States [+]  0.924
1    United Kingdom [+]  0.922
2           Germany [+]  0.936
3            France [+]  0.901
4             Japan [+]  0.909
..                  ...    ...
184           Samoa [+]  0.713
185           Yemen [+]  0.452
186    South Africa [+]  0.699
187          Zambia [+]  0.588
188        Zimbabwe [+]  0.535

[189 rows x 2 columns]

Finally I gotta fix the name of the countries. do you see that [+]? Well, it must be removed.

In [9]:
hdi['Country'] = hdi['Country'].str.rstrip(' [+]')

In [10]:
hdi

            Country    HDI
0     United States  0.924
1    United Kingdom  0.922
2           Germany  0.936
3            France  0.901
4             Japan  0.909
..              ...    ...
184           Samoa  0.713
185           Yemen  0.452
186    South Africa  0.699
187          Zambia  0.588
188        Zimbabwe  0.535

[189 rows x 2 columns]

Alright! Our HDI DataFrame is formatted. Let's format the income DataFrame.

In [11]:
income.drop(['Rank', 'Year'] , 1, inplace=True)
income.columns = ['Country', 'GDP (PPP) percapita (U$)']
income

                               Country  GDP (PPP) percapita (U$)
0                        Liechtenstein                  139100.0
1                                Qatar                  124900.0
2                               Monaco                  115700.0
3                                Macau                  114400.0
4                           Luxembourg                  109100.0
..                                 ...                       ...
225                            Liberia                     900.0
226  Congo, Democratic Republic of the                     800.0
227                            Burundi                     800.0
228           Central African Republic                     700.0
229                            Somalia                       NaN

[230 rows x 2 columns]

Now let's merge our two DataFrames. Also let's take a look at the full result of the merge, sorted by HDI. We'll also set the country name as index because the initial numeric index is not usefull at this point.

In [12]:
pd.set_option('display.max_rows', 200)

mergedDF = hdi.merge(income, left_on='Country', right_on='Country')
mergedDF.sort_values('HDI', ascending=False, inplace=True)
mergedDF.set_index('Country', inplace=True)
mergedDF

                                    HDI  GDP (PPP) percapita (U$)
Country
Norway                            0.953                   70600.0
Switzerland                       0.944                   61400.0
Australia                         0.939                   49900.0
Ireland                           0.938                   72600.0
Germany                           0.936                   50200.0
Iceland                           0.935                   52100.0
Hong Kong                         0.933                   61000.0
Sweden                            0.933                   51300.0
Singapore                         0.932                   90500.0
Netherlands                       0.931                   53600.0
Denmark                           0.929                   49600.0
Canada                            0.926                   48100.0
United States                     0.924                   59500.0
United Kingdom                    0.922                   43600.0
Finland                           0.920                   44000.0
New Zealand                       0.917                   38900.0
Liechtenstein                     0.916                  139100.0
Belgium                           0.916                   46300.0
Japan                             0.909                   42700.0
Austria                           0.908                   49200.0
Luxembourg                        0.904                  109100.0
Israel                            0.903                   36200.0
France                            0.901                   43600.0
Slovenia                          0.896                   34100.0
Spain                             0.891                   38300.0
Czech Republic                    0.888                   35200.0
Italy                             0.880                   38100.0
Malta                             0.878                   42500.0
Estonia                           0.871                   31500.0
Greece                            0.870                   27800.0
Cyprus                            0.869                   36600.0
Poland                            0.865                   29300.0
United Arab Emirates              0.863                   68200.0
Lithuania                         0.858                   31900.0
Andorra                           0.858                   49900.0
Qatar                             0.856                  124900.0
Slovakia                          0.855                   32900.0
Saudi Arabia                      0.853                   55300.0
Brunei                            0.853                   76700.0
Latvia                            0.847                   27300.0
Portugal                          0.847                   30300.0
Bahrain                           0.846                   51800.0
Chile                             0.843                   24600.0
Hungary                           0.838                   28900.0
Croatia                           0.831                   24100.0
Argentina                         0.825                   20700.0
Oman                              0.821                   45500.0
Russia                            0.816                   27900.0
Montenegro                        0.814                   17400.0
Bulgaria                          0.813                   21600.0
Romania                           0.811                   24000.0
Belarus                           0.808                   18600.0
Uruguay                           0.804                   22400.0
Kuwait                            0.803                   69700.0
Malaysia                          0.802                   28900.0
Barbados                          0.800                   17500.0
Kazakhstan                        0.800                   26100.0
Iran                              0.798                   20000.0
Palau                             0.798                   16700.0
Seychelles                        0.797                   28900.0
Costa Rica                        0.794                   17200.0
Turkey                            0.791                   26500.0
Mauritius                         0.790                   21600.0
Panama                            0.789                   24300.0
Serbia                            0.787                   15200.0
Albania                           0.785                   12500.0
Trinidad and Tobago               0.784                   31200.0
Georgia                           0.780                   10600.0
Antigua and Barbuda               0.780                   26300.0
Saint Kitts and Nevis             0.778                   26800.0
Cuba                              0.777                   11900.0
Mexico                            0.774                   19500.0
Grenada                           0.772                   14700.0
Sri Lanka                         0.770                   13000.0
Bosnia and Herzegovina            0.768                   11400.0
Venezuela                         0.761                   12400.0
Brazil                            0.759                   15500.0
North Macedonia                   0.757                   15200.0
Azerbaijan                        0.757                   17400.0
Lebanon                           0.757                   19500.0
Armenia                           0.755                    9100.0
Thailand                          0.755                   17800.0
Algeria                           0.754                   15100.0
China                             0.752                   16600.0
Ecuador                           0.752                   11200.0
Ukraine                           0.751                    8700.0
Peru                              0.750                   13300.0
Saint Lucia                       0.747                   13500.0
Colombia                          0.747                   14500.0
Mongolia                          0.741                   12600.0
Fiji                              0.741                    9900.0
Dominican Republic                0.736                   17000.0
Tunisia                           0.735                   12000.0
Jordan                            0.735                   12500.0
Jamaica                           0.732                    9200.0
Tonga                             0.726                    5600.0
Saint Vincent and the Grenadines  0.723                   11600.0
Suriname                          0.720                   13900.0
Botswana                          0.717                   18100.0
Maldives                          0.717                   19200.0
Dominica                          0.715                   12000.0
Samoa                             0.713                    5700.0
Uzbekistan                        0.710                    7000.0
Marshall Islands                  0.708                    3400.0
Belize                            0.708                    8300.0
Turkmenistan                      0.706                   18700.0
Libya                             0.706                    9800.0
Gabon                             0.702                   19300.0
Paraguay                          0.702                    9800.0
Moldova                           0.700                    5700.0
Philippines                       0.699                    8200.0
South Africa                      0.699                   13400.0
Egypt                             0.696                   13000.0
Indonesia                         0.694                   12400.0
Vietnam                           0.694                    6900.0
Bolivia                           0.693                    7500.0
Iraq                              0.685                   17000.0
El Salvador                       0.674                    8900.0
Kyrgyzstan                        0.672                    3700.0
Morocco                           0.667                    8600.0
Nicaragua                         0.658                    5800.0
Guyana                            0.654                    8300.0
Cape Verde                        0.654                    6900.0
Guatemala                         0.650                    8200.0
Tajikistan                        0.650                    3100.0
Namibia                           0.647                   11500.0
India                             0.640                    7200.0
Timor-Leste                       0.625                    5000.0
Honduras                          0.617                    5500.0
Kiribati                          0.612                    1900.0
Bhutan                            0.612                    8700.0
Bangladesh                        0.608                    4200.0
Vanuatu                           0.603                    2800.0
Laos                              0.601                    7400.0
Ghana                             0.592                    4600.0
Equatorial Guinea                 0.591                   34900.0
Kenya                             0.590                    3500.0
Zambia                            0.588                    4000.0
Cambodia                          0.582                    4000.0
Angola                            0.581                    6800.0
Nepal                             0.574                    2700.0
Pakistan                          0.562                    5400.0
Cameroon                          0.556                    3400.0
Solomon Islands                   0.546                    2100.0
Papua New Guinea                  0.544                    3800.0
Tanzania                          0.538                    3300.0
Syria                             0.536                    2900.0
Zimbabwe                          0.535                    2300.0
Nigeria                           0.532                    5900.0
Rwanda                            0.524                    2100.0
Lesotho                           0.520                    3900.0
Mauritania                        0.520                    4500.0
Madagascar                        0.519                    1600.0
Uganda                            0.516                    2400.0
Benin                             0.515                    2200.0
Senegal                           0.505                    2700.0
Comoros                           0.503                    1600.0
Togo                              0.503                    1600.0
Sudan                             0.502                    4600.0
Afghanistan                       0.498                    1900.0
Haiti                             0.498                    1800.0
Malawi                            0.477                    1200.0
Djibouti                          0.476                    3600.0
Ethiopia                          0.463                    2100.0
Guinea                            0.459                    2000.0
Guinea-Bissau                     0.455                    1800.0
Yemen                             0.452                    2300.0
Eritrea                           0.440                    1400.0
Mozambique                        0.437                    1300.0
Liberia                           0.435                     900.0
Mali                              0.427                    2200.0
Burkina Faso                      0.423                    1900.0
Sierra Leone                      0.419                    1800.0
Burundi                           0.417                     800.0
Chad                              0.404                    2400.0
South Sudan                       0.388                    1500.0
Central African Republic          0.367                     700.0
Niger                             0.354                    1200.0

Finally let's check the correlation between the two values. We'll use the `corr()` function, which calculates the correlation of all columns agains all columns.

In [13]:
mergedDF.corr()

                               HDI  GDP (PPP) percapita (U$)
HDI                       1.000000                  0.727729
GDP (PPP) percapita (U$)  0.727729                  1.000000

The `corr()` function returned a DataFrame. Since we're interested only in the correlation of the two variables, let's pinpoint what matters to us.

In [14]:
corr = mergedDF.corr().iloc[0][1]
print(f'The correlation between HDI and GDP (PPP) per capita is {corr}')

The correlation between HDI and GDP (PPP) per capita is 0.7277286705440962

There it is. As expected, there's a strong correlation between the two variables.

# Bonus: Scatter plot with Plotly
Why don't we create and nice interactive scatter plot with the information we gathered? It will allow us to visualize graphically the discovered high correlation between HDI and per capita income.

In [26]:
import plotly.offline as pyo
import plotly.graph_objs as go

x_values = mergedDF['HDI']
y_values = mergedDF['GDP (PPP) percapita (U$)']
hover_values = mergedDF.index

#Defining layout
marker = dict(size=5, line={'width':1})
layout = go.Layout(title="HDI x GDP (PPP) percapita (U$)",
                   xaxis=dict(title="HDI"),
                   yaxis=dict(title="Per capita income"))

#Defining graphical object, determining its layout and data
data = [go.Scatter(x=x_values, y=y_values, hovertext=hover_values, mode='markers',  marker=marker)]
fig = go.Figure(data=data, layout=layout)

#Generating the graph
pyo.iplot(fig)